// This file is auto-generated by generate_matches.js and modified by user schedule
export const MATCHES = [
  {
    "id": 1,
    "phase": "Group",
    "group": "A",
    "matchDay": 1,
    "date": "2026-06-11T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 1,
      "name": "Mexico",
      "shortName": "Mexico",
      "tla": "MEX",
      "flag": "🇲🇽"
    },
    "awayTeam": {
      "id": 2,
      "name": "South Africa",
      "shortName": "South Africa",
      "tla": "RSA",
      "flag": "🇿🇦"
    },
    "homeScore": 3,
    "awayScore": 1,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 87523,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 2,
    "phase": "Group",
    "group": "A",
    "matchDay": 1,
    "date": "2026-06-11T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 3,
      "name": "South Korea",
      "shortName": "South Korea",
      "tla": "KOR",
      "flag": "🇰🇷"
    },
    "awayTeam": {
      "id": 4,
      "name": "Czechia",
      "shortName": "Czechia",
      "tla": "CZE",
      "flag": "🇨🇿"
    },
    "homeScore": 2,
    "awayScore": 1,
    "stadium": {
      "name": "Estadio Akron",
      "city": "Guadalajara",
      "capacity": 46232,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 3,
    "phase": "Group",
    "group": "B",
    "matchDay": 1,
    "date": "2026-06-12T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 5,
      "name": "Canada",
      "shortName": "Canada",
      "tla": "CAN",
      "flag": "🇨🇦"
    },
    "awayTeam": {
      "id": 6,
      "name": "Bosnia and Herzegovina",
      "shortName": "Bosnia & Herz.",
      "tla": "BIH",
      "flag": "🇧🇦"
    },
    "homeScore": 1,
    "awayScore": 1,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45736,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 4,
    "phase": "Group",
    "group": "D",
    "matchDay": 1,
    "date": "2026-06-12T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 13,
      "name": "United States",
      "shortName": "USA",
      "tla": "USA",
      "flag": "🇺🇸"
    },
    "awayTeam": {
      "id": 14,
      "name": "Paraguay",
      "shortName": "Paraguay",
      "tla": "PAR",
      "flag": "🇵🇾"
    },
    "homeScore": 4,
    "awayScore": 1,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 5,
    "phase": "Group",
    "group": "C",
    "matchDay": 1,
    "date": "2026-06-13T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 11,
      "name": "Haiti",
      "shortName": "Haiti",
      "tla": "HAI",
      "flag": "🇭🇹"
    },
    "awayTeam": {
      "id": 12,
      "name": "Scotland",
      "shortName": "Scotland",
      "tla": "SCO",
      "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
    },
    "homeScore": 0,
    "awayScore": 1,
    "stadium": {
      "name": "Gillette Stadium",
      "city": "Boston",
      "capacity": 65878,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 6,
    "phase": "Group",
    "group": "D",
    "matchDay": 1,
    "date": "2026-06-13T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 15,
      "name": "Australia",
      "shortName": "Australia",
      "tla": "AUS",
      "flag": "🇦🇺"
    },
    "awayTeam": {
      "id": 16,
      "name": "Türkiye",
      "shortName": "Türkiye",
      "tla": "TUR",
      "flag": "🇹🇷"
    },
    "homeScore": 2,
    "awayScore": 0,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 7,
    "phase": "Group",
    "group": "C",
    "matchDay": 1,
    "date": "2026-06-13T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 9,
      "name": "Brazil",
      "shortName": "Brazil",
      "tla": "BRA",
      "flag": "🇧🇷"
    },
    "awayTeam": {
      "id": 10,
      "name": "Morocco",
      "shortName": "Morocco",
      "tla": "MAR",
      "flag": "🇲🇦"
    },
    "homeScore": 1,
    "awayScore": 1,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "East Rutherford",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 8,
    "phase": "Group",
    "group": "B",
    "matchDay": 1,
    "date": "2026-06-13T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 7,
      "name": "Qatar",
      "shortName": "Qatar",
      "tla": "QAT",
      "flag": "🇶🇦"
    },
    "awayTeam": {
      "id": 8,
      "name": "Switzerland",
      "shortName": "Switzerland",
      "tla": "SUI",
      "flag": "🇨🇭"
    },
    "homeScore": 1,
    "awayScore": 1,
    "stadium": {
      "name": "Levi's Stadium",
      "city": "San Francisco",
      "capacity": 68500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 9,
    "phase": "Group",
    "group": "E",
    "matchDay": 1,
    "date": "2026-06-14T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 19,
      "name": "Côte d'Ivoire",
      "shortName": "Ivory Coast",
      "tla": "CIV",
      "flag": "🇨🇮"
    },
    "awayTeam": {
      "id": 20,
      "name": "Ecuador",
      "shortName": "Ecuador",
      "tla": "ECU",
      "flag": "🇪🇨"
    },
    "homeScore": 1,
    "awayScore": 0,
    "stadium": {
      "name": "Lincoln Financial Field",
      "city": "Philadelphia",
      "capacity": 69796,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 10,
    "phase": "Group",
    "group": "E",
    "matchDay": 1,
    "date": "2026-06-14T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 17,
      "name": "Germany",
      "shortName": "Germany",
      "tla": "GER",
      "flag": "🇩🇪"
    },
    "awayTeam": {
      "id": 18,
      "name": "Curaçao",
      "shortName": "Curaçao",
      "tla": "CUW",
      "flag": "🇨🇼"
    },
    "homeScore": 7,
    "awayScore": 1,
    "stadium": {
      "name": "NRG Stadium",
      "city": "Houston",
      "capacity": 72220,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 11,
    "phase": "Group",
    "group": "F",
    "matchDay": 1,
    "date": "2026-06-14T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 21,
      "name": "Netherlands",
      "shortName": "Netherlands",
      "tla": "NED",
      "flag": "🇳🇱"
    },
    "awayTeam": {
      "id": 22,
      "name": "Japan",
      "shortName": "Japan",
      "tla": "JPN",
      "flag": "🇯🇵"
    },
    "homeScore": 2,
    "awayScore": 2,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 12,
    "phase": "Group",
    "group": "F",
    "matchDay": 1,
    "date": "2026-06-14T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 23,
      "name": "Sweden",
      "shortName": "Sweden",
      "tla": "SWE",
      "flag": "🇸🇪"
    },
    "awayTeam": {
      "id": 24,
      "name": "Tunisia",
      "shortName": "Tunisia",
      "tla": "TUN",
      "flag": "🇹🇳"
    },
    "homeScore": 5,
    "awayScore": 1,
    "stadium": {
      "name": "Estadio BBVA",
      "city": "Monterrey",
      "capacity": 53500,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 13,
    "phase": "Group",
    "group": "H",
    "matchDay": 1,
    "date": "2026-06-15T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 31,
      "name": "Saudi Arabia",
      "shortName": "Saudi Arabia",
      "tla": "KSA",
      "flag": "🇸🇦"
    },
    "awayTeam": {
      "id": 32,
      "name": "Uruguay",
      "shortName": "Uruguay",
      "tla": "URU",
      "flag": "🇺🇾"
    },
    "homeScore": 1,
    "awayScore": 1,
    "stadium": {
      "name": "Hard Rock Stadium",
      "city": "Miami",
      "capacity": 65326,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 14,
    "phase": "Group",
    "group": "H",
    "matchDay": 1,
    "date": "2026-06-15T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 29,
      "name": "Spain",
      "shortName": "Spain",
      "tla": "ESP",
      "flag": "🇪🇸"
    },
    "awayTeam": {
      "id": 30,
      "name": "Cape Verde",
      "shortName": "Cape Verde",
      "tla": "CPV",
      "flag": "🇨🇻"
    },
    "homeScore": 0,
    "awayScore": 0,
    "stadium": {
      "name": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "capacity": 71000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 15,
    "phase": "Group",
    "group": "G",
    "matchDay": 1,
    "date": "2026-06-15T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 27,
      "name": "Iran",
      "shortName": "Iran",
      "tla": "IRN",
      "flag": "🇮🇷"
    },
    "awayTeam": {
      "id": 28,
      "name": "New Zealand",
      "shortName": "New Zealand",
      "tla": "NZL",
      "flag": "🇳🇿"
    },
    "homeScore": 2,
    "awayScore": 2,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 16,
    "phase": "Group",
    "group": "G",
    "matchDay": 1,
    "date": "2026-06-15T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 25,
      "name": "Belgium",
      "shortName": "Belgium",
      "tla": "BEL",
      "flag": "🇧🇪"
    },
    "awayTeam": {
      "id": 26,
      "name": "Egypt",
      "shortName": "Egypt",
      "tla": "EGY",
      "flag": "🇪🇬"
    },
    "homeScore": 1,
    "awayScore": 1,
    "stadium": {
      "name": "Lumen Field",
      "city": "Seattle",
      "capacity": 69000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 17,
    "phase": "Group",
    "group": "I",
    "matchDay": 1,
    "date": "2026-06-16T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 33,
      "name": "France",
      "shortName": "France",
      "tla": "FRA",
      "flag": "🇫🇷"
    },
    "awayTeam": {
      "id": 34,
      "name": "Senegal",
      "shortName": "Senegal",
      "tla": "SEN",
      "flag": "🇸🇳"
    },
    "homeScore": 3,
    "awayScore": 1,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "East Rutherford",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 18,
    "phase": "Group",
    "group": "I",
    "matchDay": 1,
    "date": "2026-06-16T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 35,
      "name": "Iraq",
      "shortName": "Iraq",
      "tla": "IRQ",
      "flag": "🇮🇶"
    },
    "awayTeam": {
      "id": 36,
      "name": "Norway",
      "shortName": "Norway",
      "tla": "NOR",
      "flag": "🇳🇴"
    },
    "homeScore": 1,
    "awayScore": 4,
    "stadium": {
      "name": "Gillette Stadium",
      "city": "Boston",
      "capacity": 65878,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 19,
    "phase": "Group",
    "group": "J",
    "matchDay": 1,
    "date": "2026-06-16T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 37,
      "name": "Argentina",
      "shortName": "Argentina",
      "tla": "ARG",
      "flag": "🇦🇷"
    },
    "awayTeam": {
      "id": 38,
      "name": "Algeria",
      "shortName": "Algeria",
      "tla": "ALG",
      "flag": "🇩🇿"
    },
    "homeScore": 3,
    "awayScore": 0,
    "stadium": {
      "name": "GEHA Field at Arrowhead Stadium",
      "city": "Kansas City",
      "capacity": 76416,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 20,
    "phase": "Group",
    "group": "J",
    "matchDay": 1,
    "date": "2026-06-16T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 39,
      "name": "Austria",
      "shortName": "Austria",
      "tla": "AUT",
      "flag": "🇦🇹"
    },
    "awayTeam": {
      "id": 40,
      "name": "Jordan",
      "shortName": "Jordan",
      "tla": "JOR",
      "flag": "🇯🇴"
    },
    "homeScore": 3,
    "awayScore": 1,
    "stadium": {
      "name": "Levi's Stadium",
      "city": "San Francisco",
      "capacity": 68500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 21,
    "phase": "Group",
    "group": "L",
    "matchDay": 2,
    "date": "2026-06-17T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 47,
      "name": "Ghana",
      "shortName": "Ghana",
      "tla": "GHA",
      "flag": "🇬🇭"
    },
    "awayTeam": {
      "id": 48,
      "name": "Panama",
      "shortName": "Panama",
      "tla": "PAN",
      "flag": "🇵🇦"
    },
    "homeScore": 1,
    "awayScore": 0,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45736,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 22,
    "phase": "Group",
    "group": "L",
    "matchDay": 2,
    "date": "2026-06-17T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 45,
      "name": "England",
      "shortName": "England",
      "tla": "ENG",
      "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
    },
    "awayTeam": {
      "id": 46,
      "name": "Croatia",
      "shortName": "Croatia",
      "tla": "CRO",
      "flag": "🇭🇷"
    },
    "homeScore": 4,
    "awayScore": 2,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 23,
    "phase": "Group",
    "group": "K",
    "matchDay": 2,
    "date": "2026-06-17T20:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 41,
      "name": "Portugal",
      "shortName": "Portugal",
      "tla": "POR",
      "flag": "🇵🇹"
    },
    "awayTeam": {
      "id": 42,
      "name": "DR Congo",
      "shortName": "DR Congo",
      "tla": "COD",
      "flag": "🇨🇩"
    },
    "homeScore": 1,
    "awayScore": 1,
    "stadium": {
      "name": "NRG Stadium",
      "city": "Houston",
      "capacity": 72220,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 24,
    "phase": "Group",
    "group": "K",
    "matchDay": 2,
    "date": "2026-06-18T23:00:00.000Z",
    "status": "FINISHED",
    "homeTeam": {
      "id": 43,
      "name": "Uzbekistan",
      "shortName": "Uzbekistan",
      "tla": "UZB",
      "flag": "🇺🇿"
    },
    "awayTeam": {
      "id": 44,
      "name": "Colombia",
      "shortName": "Colombia",
      "tla": "COL",
      "flag": "🇨🇴"
    },
    "homeScore": 1,
    "awayScore": 3,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 87523,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 25,
    "phase": "Group",
    "group": "A",
    "matchDay": 2,
    "date": "2026-06-18T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 4,
      "name": "Czechia",
      "shortName": "Czechia",
      "tla": "CZE",
      "flag": "🇨🇿"
    },
    "awayTeam": {
      "id": 2,
      "name": "South Africa",
      "shortName": "South Africa",
      "tla": "RSA",
      "flag": "🇿🇦"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "capacity": 71000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 26,
    "phase": "Group",
    "group": "B",
    "matchDay": 2,
    "date": "2026-06-18T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 8,
      "name": "Switzerland",
      "shortName": "Switzerland",
      "tla": "SUI",
      "flag": "🇨🇭"
    },
    "awayTeam": {
      "id": 6,
      "name": "UEFA Playoff Winner",
      "shortName": "UEFA PO",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 27,
    "phase": "Group",
    "group": "B",
    "matchDay": 2,
    "date": "2026-06-18T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 5,
      "name": "Canada",
      "shortName": "Canada",
      "tla": "CAN",
      "flag": "🇨🇦"
    },
    "awayTeam": {
      "id": 7,
      "name": "Qatar",
      "shortName": "Qatar",
      "tla": "QAT",
      "flag": "🇶🇦"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 28,
    "phase": "Group",
    "group": "A",
    "matchDay": 2,
    "date": "2026-06-18T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 1,
      "name": "Mexico",
      "shortName": "Mexico",
      "tla": "MEX",
      "flag": "🇲🇽"
    },
    "awayTeam": {
      "id": 3,
      "name": "South Korea",
      "shortName": "South Korea",
      "tla": "KOR",
      "flag": "🇰🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Akron",
      "city": "Guadalajara",
      "capacity": 46232,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 29,
    "phase": "Group",
    "group": "C",
    "matchDay": 2,
    "date": "2026-06-19T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 9,
      "name": "Brazil",
      "shortName": "Brazil",
      "tla": "BRA",
      "flag": "🇧🇷"
    },
    "awayTeam": {
      "id": 11,
      "name": "Haiti",
      "shortName": "Haiti",
      "tla": "HAI",
      "flag": "🇭🇹"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Lincoln Financial Field",
      "city": "Philadelphia",
      "capacity": 69796,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 30,
    "phase": "Group",
    "group": "C",
    "matchDay": 2,
    "date": "2026-06-19T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 12,
      "name": "Scotland",
      "shortName": "Scotland",
      "tla": "SCO",
      "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
    },
    "awayTeam": {
      "id": 10,
      "name": "Morocco",
      "shortName": "Morocco",
      "tla": "MAR",
      "flag": "🇲🇦"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Gillette Stadium",
      "city": "Boston",
      "capacity": 65878,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 31,
    "phase": "Group",
    "group": "D",
    "matchDay": 2,
    "date": "2026-06-19T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 16,
      "name": "Türkiye",
      "shortName": "Türkiye",
      "tla": "TUR",
      "flag": "🇹🇷"
    },
    "awayTeam": {
      "id": 14,
      "name": "Paraguay",
      "shortName": "Paraguay",
      "tla": "PAR",
      "flag": "🇵🇾"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Levi's Stadium",
      "city": "San Francisco",
      "capacity": 68500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 32,
    "phase": "Group",
    "group": "D",
    "matchDay": 2,
    "date": "2026-06-19T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 13,
      "name": "United States",
      "shortName": "USA",
      "tla": "USA",
      "flag": "🇺🇸"
    },
    "awayTeam": {
      "id": 15,
      "name": "Australia",
      "shortName": "Australia",
      "tla": "AUS",
      "flag": "🇦🇺"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Lumen Field",
      "city": "Seattle",
      "capacity": 69000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 33,
    "phase": "Group",
    "group": "E",
    "matchDay": 2,
    "date": "2026-06-20T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 17,
      "name": "Germany",
      "shortName": "Germany",
      "tla": "GER",
      "flag": "🇩🇪"
    },
    "awayTeam": {
      "id": 19,
      "name": "Côte d'Ivoire",
      "shortName": "Ivory Coast",
      "tla": "CIV",
      "flag": "🇨🇮"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45736,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 34,
    "phase": "Group",
    "group": "E",
    "matchDay": 2,
    "date": "2026-06-20T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 20,
      "name": "Ecuador",
      "shortName": "Ecuador",
      "tla": "ECU",
      "flag": "🇪🇨"
    },
    "awayTeam": {
      "id": 18,
      "name": "Curaçao",
      "shortName": "Curaçao",
      "tla": "CUW",
      "flag": "🇨🇼"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "GEHA Field at Arrowhead Stadium",
      "city": "Kansas City",
      "capacity": 76416,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 35,
    "phase": "Group",
    "group": "F",
    "matchDay": 2,
    "date": "2026-06-20T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 21,
      "name": "Netherlands",
      "shortName": "Netherlands",
      "tla": "NED",
      "flag": "🇳🇱"
    },
    "awayTeam": {
      "id": 23,
      "name": "Sweden",
      "shortName": "Sweden",
      "tla": "SWE",
      "flag": "🇸🇪"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "NRG Stadium",
      "city": "Houston",
      "capacity": 72220,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 36,
    "phase": "Group",
    "group": "F",
    "matchDay": 2,
    "date": "2026-06-21T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 24,
      "name": "Tunisia",
      "shortName": "Tunisia",
      "tla": "TUN",
      "flag": "🇹🇳"
    },
    "awayTeam": {
      "id": 22,
      "name": "Japan",
      "shortName": "Japan",
      "tla": "JPN",
      "flag": "🇯🇵"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio BBVA",
      "city": "Monterrey",
      "capacity": 53500,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 37,
    "phase": "Group",
    "group": "H",
    "matchDay": 2,
    "date": "2026-06-21T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 32,
      "name": "Uruguay",
      "shortName": "Uruguay",
      "tla": "URU",
      "flag": "🇺🇾"
    },
    "awayTeam": {
      "id": 30,
      "name": "Cape Verde",
      "shortName": "Cape Verde",
      "tla": "CPV",
      "flag": "🇨🇻"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Hard Rock Stadium",
      "city": "Miami",
      "capacity": 65326,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 38,
    "phase": "Group",
    "group": "H",
    "matchDay": 2,
    "date": "2026-06-21T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 29,
      "name": "Spain",
      "shortName": "Spain",
      "tla": "ESP",
      "flag": "🇪🇸"
    },
    "awayTeam": {
      "id": 31,
      "name": "Saudi Arabia",
      "shortName": "Saudi Arabia",
      "tla": "KSA",
      "flag": "🇸🇦"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "capacity": 71000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 39,
    "phase": "Group",
    "group": "G",
    "matchDay": 2,
    "date": "2026-06-21T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 25,
      "name": "Belgium",
      "shortName": "Belgium",
      "tla": "BEL",
      "flag": "🇧🇪"
    },
    "awayTeam": {
      "id": 27,
      "name": "Iran",
      "shortName": "Iran",
      "tla": "IRN",
      "flag": "🇮🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 40,
    "phase": "Group",
    "group": "G",
    "matchDay": 2,
    "date": "2026-06-21T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 28,
      "name": "New Zealand",
      "shortName": "New Zealand",
      "tla": "NZL",
      "flag": "🇳🇿"
    },
    "awayTeam": {
      "id": 26,
      "name": "Egypt",
      "shortName": "Egypt",
      "tla": "EGY",
      "flag": "🇪🇬"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 41,
    "phase": "Group",
    "group": "I",
    "matchDay": 2,
    "date": "2026-06-22T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 36,
      "name": "Norway",
      "shortName": "Norway",
      "tla": "NOR",
      "flag": "🇳🇴"
    },
    "awayTeam": {
      "id": 34,
      "name": "Senegal",
      "shortName": "Senegal",
      "tla": "SEN",
      "flag": "🇸🇳"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "East Rutherford",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 42,
    "phase": "Group",
    "group": "I",
    "matchDay": 2,
    "date": "2026-06-22T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 33,
      "name": "France",
      "shortName": "France",
      "tla": "FRA",
      "flag": "🇫🇷"
    },
    "awayTeam": {
      "id": 35,
      "name": "Iraq",
      "shortName": "Iraq",
      "tla": "IRQ",
      "flag": "🇮🇶"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Lincoln Financial Field",
      "city": "Philadelphia",
      "capacity": 69796,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 43,
    "phase": "Group",
    "group": "J",
    "matchDay": 2,
    "date": "2026-06-22T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 37,
      "name": "Argentina",
      "shortName": "Argentina",
      "tla": "ARG",
      "flag": "🇦🇷"
    },
    "awayTeam": {
      "id": 39,
      "name": "Austria",
      "shortName": "Austria",
      "tla": "AUT",
      "flag": "🇦🇹"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 44,
    "phase": "Group",
    "group": "J",
    "matchDay": 2,
    "date": "2026-06-22T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 40,
      "name": "Jordan",
      "shortName": "Jordan",
      "tla": "JOR",
      "flag": "🇯🇴"
    },
    "awayTeam": {
      "id": 38,
      "name": "Algeria",
      "shortName": "Algeria",
      "tla": "ALG",
      "flag": "🇩🇿"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Levi's Stadium",
      "city": "San Francisco",
      "capacity": 68500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 45,
    "phase": "Group",
    "group": "L",
    "matchDay": 3,
    "date": "2026-06-23T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 45,
      "name": "England",
      "shortName": "England",
      "tla": "ENG",
      "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
    },
    "awayTeam": {
      "id": 47,
      "name": "Ghana",
      "shortName": "Ghana",
      "tla": "GHA",
      "flag": "🇬🇭"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Gillette Stadium",
      "city": "Boston",
      "capacity": 65878,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 46,
    "phase": "Group",
    "group": "L",
    "matchDay": 3,
    "date": "2026-06-23T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 48,
      "name": "Panama",
      "shortName": "Panama",
      "tla": "PAN",
      "flag": "🇵🇦"
    },
    "awayTeam": {
      "id": 46,
      "name": "Croatia",
      "shortName": "Croatia",
      "tla": "CRO",
      "flag": "🇭🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45736,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 47,
    "phase": "Group",
    "group": "K",
    "matchDay": 3,
    "date": "2026-06-23T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 41,
      "name": "Portugal",
      "shortName": "Portugal",
      "tla": "POR",
      "flag": "🇵🇹"
    },
    "awayTeam": {
      "id": 43,
      "name": "Uzbekistan",
      "shortName": "Uzbekistan",
      "tla": "UZB",
      "flag": "🇺🇿"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "NRG Stadium",
      "city": "Houston",
      "capacity": 72220,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 48,
    "phase": "Group",
    "group": "K",
    "matchDay": 3,
    "date": "2026-06-23T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 44,
      "name": "Colombia",
      "shortName": "Colombia",
      "tla": "COL",
      "flag": "🇨🇴"
    },
    "awayTeam": {
      "id": 42,
      "name": "DR Congo",
      "shortName": "DR Congo",
      "tla": "COD",
      "flag": "🇨🇩"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Akron",
      "city": "Guadalajara",
      "capacity": 46232,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 49,
    "phase": "Group",
    "group": "C",
    "matchDay": 3,
    "date": "2026-06-24T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 12,
      "name": "Scotland",
      "shortName": "Scotland",
      "tla": "SCO",
      "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
    },
    "awayTeam": {
      "id": 9,
      "name": "Brazil",
      "shortName": "Brazil",
      "tla": "BRA",
      "flag": "🇧🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Hard Rock Stadium",
      "city": "Miami",
      "capacity": 65326,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 50,
    "phase": "Group",
    "group": "C",
    "matchDay": 3,
    "date": "2026-06-24T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 10,
      "name": "Morocco",
      "shortName": "Morocco",
      "tla": "MAR",
      "flag": "🇲🇦"
    },
    "awayTeam": {
      "id": 11,
      "name": "Haiti",
      "shortName": "Haiti",
      "tla": "HAI",
      "flag": "🇭🇹"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "capacity": 71000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 51,
    "phase": "Group",
    "group": "B",
    "matchDay": 3,
    "date": "2026-06-24T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 8,
      "name": "Switzerland",
      "shortName": "Switzerland",
      "tla": "SUI",
      "flag": "🇨🇭"
    },
    "awayTeam": {
      "id": 5,
      "name": "Canada",
      "shortName": "Canada",
      "tla": "CAN",
      "flag": "🇨🇦"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 52,
    "phase": "Group",
    "group": "B",
    "matchDay": 3,
    "date": "2026-06-24T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 6,
      "name": "UEFA Playoff Winner",
      "shortName": "UEFA PO",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 7,
      "name": "Qatar",
      "shortName": "Qatar",
      "tla": "QAT",
      "flag": "🇶🇦"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Lumen Field",
      "city": "Seattle",
      "capacity": 69000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 53,
    "phase": "Group",
    "group": "A",
    "matchDay": 3,
    "date": "2026-06-24T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 4,
      "name": "Czechia",
      "shortName": "Czechia",
      "tla": "CZE",
      "flag": "🇨🇿"
    },
    "awayTeam": {
      "id": 1,
      "name": "Mexico",
      "shortName": "Mexico",
      "tla": "MEX",
      "flag": "🇲🇽"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 87523,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 54,
    "phase": "Group",
    "group": "A",
    "matchDay": 3,
    "date": "2026-06-24T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 2,
      "name": "South Africa",
      "shortName": "South Africa",
      "tla": "RSA",
      "flag": "🇿🇦"
    },
    "awayTeam": {
      "id": 3,
      "name": "South Korea",
      "shortName": "South Korea",
      "tla": "KOR",
      "flag": "🇰🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio BBVA",
      "city": "Monterrey",
      "capacity": 53500,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 55,
    "phase": "Group",
    "group": "E",
    "matchDay": 3,
    "date": "2026-06-25T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 18,
      "name": "Curaçao",
      "shortName": "Curaçao",
      "tla": "CUW",
      "flag": "🇨🇼"
    },
    "awayTeam": {
      "id": 19,
      "name": "Côte d'Ivoire",
      "shortName": "Ivory Coast",
      "tla": "CIV",
      "flag": "🇨🇮"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Lincoln Financial Field",
      "city": "Philadelphia",
      "capacity": 69796,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 56,
    "phase": "Group",
    "group": "E",
    "matchDay": 3,
    "date": "2026-06-25T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 20,
      "name": "Ecuador",
      "shortName": "Ecuador",
      "tla": "ECU",
      "flag": "🇪🇨"
    },
    "awayTeam": {
      "id": 17,
      "name": "Germany",
      "shortName": "Germany",
      "tla": "GER",
      "flag": "🇩🇪"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "East Rutherford",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 57,
    "phase": "Group",
    "group": "F",
    "matchDay": 3,
    "date": "2026-06-25T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 22,
      "name": "Japan",
      "shortName": "Japan",
      "tla": "JPN",
      "flag": "🇯🇵"
    },
    "awayTeam": {
      "id": 23,
      "name": "Sweden",
      "shortName": "Sweden",
      "tla": "SWE",
      "flag": "🇸🇪"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 58,
    "phase": "Group",
    "group": "F",
    "matchDay": 3,
    "date": "2026-06-25T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 24,
      "name": "Tunisia",
      "shortName": "Tunisia",
      "tla": "TUN",
      "flag": "🇹🇳"
    },
    "awayTeam": {
      "id": 21,
      "name": "Netherlands",
      "shortName": "Netherlands",
      "tla": "NED",
      "flag": "🇳🇱"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "GEHA Field at Arrowhead Stadium",
      "city": "Kansas City",
      "capacity": 76416,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 59,
    "phase": "Group",
    "group": "D",
    "matchDay": 3,
    "date": "2026-06-25T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 16,
      "name": "Türkiye",
      "shortName": "Türkiye",
      "tla": "TUR",
      "flag": "🇹🇷"
    },
    "awayTeam": {
      "id": 13,
      "name": "United States",
      "shortName": "USA",
      "tla": "USA",
      "flag": "🇺🇸"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 60,
    "phase": "Group",
    "group": "D",
    "matchDay": 3,
    "date": "2026-06-26T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 14,
      "name": "Paraguay",
      "shortName": "Paraguay",
      "tla": "PAR",
      "flag": "🇵🇾"
    },
    "awayTeam": {
      "id": 15,
      "name": "Australia",
      "shortName": "Australia",
      "tla": "AUS",
      "flag": "🇦🇺"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Levi's Stadium",
      "city": "San Francisco",
      "capacity": 68500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 61,
    "phase": "Group",
    "group": "I",
    "matchDay": 3,
    "date": "2026-06-26T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 36,
      "name": "Norway",
      "shortName": "Norway",
      "tla": "NOR",
      "flag": "🇳🇴"
    },
    "awayTeam": {
      "id": 33,
      "name": "France",
      "shortName": "France",
      "tla": "FRA",
      "flag": "🇫🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Gillette Stadium",
      "city": "Boston",
      "capacity": 65878,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 62,
    "phase": "Group",
    "group": "I",
    "matchDay": 3,
    "date": "2026-06-26T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 34,
      "name": "Senegal",
      "shortName": "Senegal",
      "tla": "SEN",
      "flag": "🇸🇳"
    },
    "awayTeam": {
      "id": 35,
      "name": "Iraq",
      "shortName": "Iraq",
      "tla": "IRQ",
      "flag": "🇮🇶"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45736,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 63,
    "phase": "Group",
    "group": "G",
    "matchDay": 3,
    "date": "2026-06-26T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 26,
      "name": "Egypt",
      "shortName": "Egypt",
      "tla": "EGY",
      "flag": "🇪🇬"
    },
    "awayTeam": {
      "id": 27,
      "name": "Iran",
      "shortName": "Iran",
      "tla": "IRN",
      "flag": "🇮🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Lumen Field",
      "city": "Seattle",
      "capacity": 69000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 64,
    "phase": "Group",
    "group": "G",
    "matchDay": 3,
    "date": "2026-06-26T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 28,
      "name": "New Zealand",
      "shortName": "New Zealand",
      "tla": "NZL",
      "flag": "🇳🇿"
    },
    "awayTeam": {
      "id": 25,
      "name": "Belgium",
      "shortName": "Belgium",
      "tla": "BEL",
      "flag": "🇧🇪"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 65,
    "phase": "Group",
    "group": "H",
    "matchDay": 3,
    "date": "2026-06-26T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 30,
      "name": "Cape Verde",
      "shortName": "Cape Verde",
      "tla": "CPV",
      "flag": "🇨🇻"
    },
    "awayTeam": {
      "id": 31,
      "name": "Saudi Arabia",
      "shortName": "Saudi Arabia",
      "tla": "KSA",
      "flag": "🇸🇦"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "NRG Stadium",
      "city": "Houston",
      "capacity": 72220,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 66,
    "phase": "Group",
    "group": "H",
    "matchDay": 3,
    "date": "2026-06-26T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 32,
      "name": "Uruguay",
      "shortName": "Uruguay",
      "tla": "URU",
      "flag": "🇺🇾"
    },
    "awayTeam": {
      "id": 29,
      "name": "Spain",
      "shortName": "Spain",
      "tla": "ESP",
      "flag": "🇪🇸"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Akron",
      "city": "Guadalajara",
      "capacity": 46232,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 67,
    "phase": "Group",
    "group": "L",
    "matchDay": 3,
    "date": "2026-06-27T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 48,
      "name": "Panama",
      "shortName": "Panama",
      "tla": "PAN",
      "flag": "🇵🇦"
    },
    "awayTeam": {
      "id": 45,
      "name": "England",
      "shortName": "England",
      "tla": "ENG",
      "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "East Rutherford",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 68,
    "phase": "Group",
    "group": "L",
    "matchDay": 3,
    "date": "2026-06-27T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 46,
      "name": "Croatia",
      "shortName": "Croatia",
      "tla": "CRO",
      "flag": "🇭🇷"
    },
    "awayTeam": {
      "id": 47,
      "name": "Ghana",
      "shortName": "Ghana",
      "tla": "GHA",
      "flag": "🇬🇭"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Lincoln Financial Field",
      "city": "Philadelphia",
      "capacity": 69796,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 69,
    "phase": "Group",
    "group": "J",
    "matchDay": 3,
    "date": "2026-06-27T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 38,
      "name": "Algeria",
      "shortName": "Algeria",
      "tla": "ALG",
      "flag": "🇩🇿"
    },
    "awayTeam": {
      "id": 39,
      "name": "Austria",
      "shortName": "Austria",
      "tla": "AUT",
      "flag": "🇦🇹"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "GEHA Field at Arrowhead Stadium",
      "city": "Kansas City",
      "capacity": 76416,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 70,
    "phase": "Group",
    "group": "J",
    "matchDay": 3,
    "date": "2026-06-27T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 40,
      "name": "Jordan",
      "shortName": "Jordan",
      "tla": "JOR",
      "flag": "🇯🇴"
    },
    "awayTeam": {
      "id": 37,
      "name": "Argentina",
      "shortName": "Argentina",
      "tla": "ARG",
      "flag": "🇦🇷"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 71,
    "phase": "Group",
    "group": "K",
    "matchDay": 3,
    "date": "2026-06-27T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 44,
      "name": "Colombia",
      "shortName": "Colombia",
      "tla": "COL",
      "flag": "🇨🇴"
    },
    "awayTeam": {
      "id": 41,
      "name": "Portugal",
      "shortName": "Portugal",
      "tla": "POR",
      "flag": "🇵🇹"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Hard Rock Stadium",
      "city": "Miami",
      "capacity": 65326,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 72,
    "phase": "Group",
    "group": "K",
    "matchDay": 3,
    "date": "2026-06-27T23:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 42,
      "name": "DR Congo",
      "shortName": "DR Congo",
      "tla": "COD",
      "flag": "🇨🇩"
    },
    "awayTeam": {
      "id": 43,
      "name": "Uzbekistan",
      "shortName": "Uzbekistan",
      "tla": "UZB",
      "flag": "🇺🇿"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Mercedes-Benz Stadium",
      "city": "Atlanta",
      "capacity": 71000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 73,
    "phase": "Round of 32",
    "date": "2026-06-22T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 973,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1023,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 74,
    "phase": "Round of 32",
    "date": "2026-06-23T00:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 974,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1024,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 75,
    "phase": "Round of 32",
    "date": "2026-06-23T04:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 975,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1025,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 76,
    "phase": "Round of 32",
    "date": "2026-06-23T08:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 976,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1026,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45000,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 77,
    "phase": "Round of 32",
    "date": "2026-06-23T12:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 977,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1027,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 78,
    "phase": "Round of 32",
    "date": "2026-06-23T16:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 978,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1028,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 79,
    "phase": "Round of 32",
    "date": "2026-06-23T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 979,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1029,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "New York/New Jersey",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 80,
    "phase": "Round of 32",
    "date": "2026-06-24T00:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 980,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1030,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "New York/New Jersey",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 81,
    "phase": "Round of 32",
    "date": "2026-06-24T04:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 981,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1031,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 82,
    "phase": "Round of 32",
    "date": "2026-06-24T08:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 982,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1032,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 83,
    "phase": "Round of 32",
    "date": "2026-06-24T12:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 983,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1033,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 84,
    "phase": "Round of 32",
    "date": "2026-06-24T16:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 984,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1034,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 85,
    "phase": "Round of 32",
    "date": "2026-06-24T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 985,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1035,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 86,
    "phase": "Round of 32",
    "date": "2026-06-25T00:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 986,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1036,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45000,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 87,
    "phase": "Round of 32",
    "date": "2026-06-25T04:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 987,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1037,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45000,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 88,
    "phase": "Round of 32",
    "date": "2026-06-25T08:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 988,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1038,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "New York/New Jersey",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 89,
    "phase": "Round of 16",
    "date": "2026-06-27T12:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 989,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1039,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 90,
    "phase": "Round of 16",
    "date": "2026-06-27T16:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 990,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1040,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45000,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 91,
    "phase": "Round of 16",
    "date": "2026-06-27T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 991,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1041,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 92,
    "phase": "Round of 16",
    "date": "2026-06-28T00:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 992,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1042,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 93,
    "phase": "Round of 16",
    "date": "2026-06-28T04:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 993,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1043,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 94,
    "phase": "Round of 16",
    "date": "2026-06-28T08:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 994,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1044,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 95,
    "phase": "Round of 16",
    "date": "2026-06-28T12:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 995,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1045,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BMO Field",
      "city": "Toronto",
      "capacity": 45000,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 96,
    "phase": "Round of 16",
    "date": "2026-06-28T16:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 996,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1046,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "SoFi Stadium",
      "city": "Los Angeles",
      "capacity": 70240,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 97,
    "phase": "Quarter-finals",
    "date": "2026-06-30T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 997,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1047,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 98,
    "phase": "Quarter-finals",
    "date": "2026-07-01T00:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 998,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1048,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "AT&T Stadium",
      "city": "Dallas",
      "capacity": 80000,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 99,
    "phase": "Quarter-finals",
    "date": "2026-07-01T04:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 999,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1049,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 100,
    "phase": "Quarter-finals",
    "date": "2026-07-01T08:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 1000,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1050,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "BC Place",
      "city": "Vancouver",
      "capacity": 54500,
      "countryFlag": "🇨🇦"
    }
  },
  {
    "id": 101,
    "phase": "Semi-finals",
    "date": "2026-07-03T12:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 1001,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1051,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 102,
    "phase": "Semi-finals",
    "date": "2026-07-03T16:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 1002,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1052,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "MetLife Stadium",
      "city": "New York/New Jersey",
      "capacity": 82500,
      "countryFlag": "🇺🇸"
    }
  },
  {
    "id": 103,
    "phase": "Third place play-off",
    "date": "2026-07-05T20:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 1003,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1053,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  },
  {
    "id": 104,
    "phase": "Final",
    "date": "2026-07-08T00:00:00.000Z",
    "status": "SCHEDULED",
    "homeTeam": {
      "id": 1004,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "awayTeam": {
      "id": 1054,
      "name": "TBD",
      "shortName": "TBD",
      "tla": "TBD",
      "flag": "🏳️"
    },
    "homeScore": null,
    "awayScore": null,
    "stadium": {
      "name": "Estadio Azteca",
      "city": "Mexico City",
      "capacity": 83264,
      "countryFlag": "🇲🇽"
    }
  }
];
